openapi: "3.0.2"
info:
  version: "0.1"
  title: Compliance check simulation
  description:
    Simulation of a compliance check service, for demonstration purposes
servers:
  - url: "{protocol}://hostname:<port>/switch/"
    variables:
      protocol:
        enum:
          - http
          - https
        default: https

paths:
  /compliance-check/{ID}:
    get:
      tags:
        - compliance
      description: Returns compliance checks performed and score
      operationId: complianceCheckById
      parameters:
        - name: ID
          in: path
          description: ID on which the checks are to be performed
          required: true
          schema:
            type: string
        - name: FirstName
          in: query
          description: First name accompnaying the ID
          schema:
            type: string
        - name: LastName
          in: query
          description: Last name accompnaying the ID
          schema:
            type: string
        - name: Currency
          in: query
          description: Currency accompnaying the ID
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/complianceResponse'          
        '400':
          description: Invalid ID supplied
        '404':
          description: ID not found
    

components:
  schemas:
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: tag
    complianceResponse:
      required:
        - rulesList
        - listOfChecks
        - weightedScore
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        weightedScore:
          type: integer
          format: int64
          example: 75
        listOfChecks:  
          type: array
          items:
            type: string
        rulesList:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: status
          enum:
            - available
            - pending
            - sold
        additionalInfo:
          type: string

  requestBodies:
    complianceResponse:
      description: compliance check response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/complianceResponse'
